FROM ubuntu:24.04 AS build

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update &&  apt install -y \
    wget \
    make \
    git


RUN wget https://musl.cc/arm-linux-musleabi-cross.tgz
RUN tar xf arm-linux-musleabi-cross.tgz
RUN ln -s /arm-linux-musleabi-cross/bin/arm-linux-musleabi-ar /bin/ar
RUN ln -s /arm-linux-musleabi-cross/bin/arm-linux-musleabi-ranlib /bin/ranlib

ENV PATH=/arm-linux-musleabi-cross/bin:$PATH


